#!/bin/bash
read -p "Package name: " name
while ( true ); 
do
	lspkg=($(apt-cache pkgnames))

	if [[ "${lspkg[*]}" == *"$name"* ]]; 
	then
		#apt-cache show $name	
		a=`apt-cache show $name|cut -d" " -f-1| cut -d":" -f-1`
		n=`echo $a|wc -w`
		s=`apt-cache show $name`
		
		read -p "Attributrs : " attributrs

		for((i=1;i <= $n;i++)); 
		do
        		a[$i]=`echo $a|cut -d" " -f$i`
		done

		for((i=1; i <= $n; i++)); 
		do
			if [ ${a[$i]} == $attributrs ]
			then
				b=${s#*${a[$i-1]}}
				b=${b#*${a[$i]}":"}
				b=${b%${a[$i+1]}":"*}
				echo $attributrs":"$b
			fi
		done
	fi
	echo "Package name:"
	read name
done
